name: Code Quality (Oxlint)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-oxlint:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Roda o Oxlint Oficial direto do ecossistema deles, sem precisar de Node ou npm install
      - name: Run Oxlint Action
        uses: oxc-project/oxlint-action@v1
        with:
          # Adiciona a regra para falhar o build caso existam avisos ou erros
          params: --deny-warnings
